/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estagio.view;

import DAO.BairroDao;
import DAO.CidadeDao;
import DAO.LogradouroDao;
import br.com.estagio.factory.EntityManagerUtil;
import br.com.estagio.model.Bairro;
import br.com.estagio.model.Candidato;
import br.com.estagio.model.Cidade;
import br.com.estagio.model.Curso;
import br.com.estagio.model.Endereco;
import br.com.estagio.model.Habilidade;
import br.com.estagio.model.Logradouro;
import br.com.estagio.model.PessoaJuridica;
import br.com.estagio.model.Vaga;
import controller.CandidatoController;
import controller.CidadeController;
import controller.VagaController;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.sql.Date;
import java.text.ParseException;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;

/**
 *
 * @author victor
 */
public class CandidatoJF extends javax.swing.JInternalFrame {
    
    Candidato candidato;
    Endereco endereco;
    Logradouro logradouro;
    Bairro bairro;
    Cidade cidade;
    Curso curso;
    
   
    CandidatoController candidatoC;
    CidadeController cidadeController;
    
    List<Curso> listCurso;
    List<PessoaJuridica> listPJ;
    DefaultListModel lm;
    List<Habilidade> listH;
    List<Habilidade> h;
    
    public CandidatoJF() {
        initComponents();
        
        h = null;
        
        candidato = new Candidato();
        candidatoC = new CandidatoController();
        
        endereco = new Endereco();
        logradouro = new Logradouro();
        bairro = new Bairro();
        cidade = new Cidade();
        cidadeController = new CidadeController();
       
           
     
      populaCurso();
      populaCidade();
      populaSexo();
      populaTurno();
      populaSituacaoCurso();
      populaInstituicao();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_nomeCandidato = new javax.swing.JLabel();
        LB_CPF = new javax.swing.JLabel();
        B_cadastrar = new javax.swing.JButton();
        TF_nomeCandidato = new javax.swing.JTextField();
        TF_CPFCandidato = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##");
            TF_CPFCandidato = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){
        }
        LB_RG = new javax.swing.JLabel();
        TF_RGCandidato = new javax.swing.JTextField();
        LB_sexo = new javax.swing.JLabel();
        combo_sexo = new javax.swing.JComboBox();
        LB_dtNascimento = new javax.swing.JLabel();
        TF_dtNascimento = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            TF_dtNascimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        LB_logradouro = new javax.swing.JLabel();
        TF_logradouro = new javax.swing.JTextField();
        LB_numeroEndereco = new javax.swing.JLabel();
        TF_numeroEndereco = new javax.swing.JTextField();
        LB_complementoEndereco = new javax.swing.JLabel();
        TF_complementoEndereco = new javax.swing.JTextField();
        LB_bairro = new javax.swing.JLabel();
        TF_bairro = new javax.swing.JTextField();
        LB_bairro1 = new javax.swing.JLabel();
        LB_cidade = new javax.swing.JLabel();
        combo_cidade = new javax.swing.JComboBox();
        LB_celular = new javax.swing.JLabel();
        TF_celular = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cel = new javax.swing.text.MaskFormatter("(##)####-####");
            TF_celular = new javax.swing.JFormattedTextField(cel);
        }
        catch (Exception e){
        }
        LB_telefone = new javax.swing.JLabel();
        TF_telefone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tel = new javax.swing.text.MaskFormatter("(##)####-####");
            TF_telefone = new javax.swing.JFormattedTextField(tel);
        }
        catch (Exception e){
        }
        LB_CEP = new javax.swing.JLabel();
        TF_CEP = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cep = new javax.swing.text.MaskFormatter("##.###-###");
            TF_CEP = new javax.swing.JFormattedTextField(cep);
        }
        catch (Exception e){
        }
        LB_escolaridade = new javax.swing.JLabel();
        combo_escolaridade = new javax.swing.JComboBox();
        combo_turno = new javax.swing.JComboBox();
        LB_turno = new javax.swing.JLabel();
        LB_instituicao = new javax.swing.JLabel();
        combo_instituicao = new javax.swing.JComboBox();
        LB_curso = new javax.swing.JLabel();
        combo_curso = new javax.swing.JComboBox();
        LB_situacaoCurso = new javax.swing.JLabel();
        LB_dtConclusaoCurso = new javax.swing.JLabel();
        combo_situacaoCurso = new javax.swing.JComboBox();
        TF_dtConclusaoCurso = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            TF_dtConclusaoCurso = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        B_limpar = new javax.swing.JButton();
        LB_tipoLogradouro = new javax.swing.JLabel();
        combo_tipoLogradouro = new javax.swing.JComboBox();
        LB_UF = new javax.swing.JLabel();
        TF_UF = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Vagas");
        setAutoscrolls(true);

        LB_nomeCandidato.setText("Nome:");

        LB_CPF.setText("CPF:");

        B_cadastrar.setText("Cadastrar");
        B_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cadastrarActionPerformed(evt);
            }
        });

        TF_CPFCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CPFCandidatoActionPerformed(evt);
            }
        });

        LB_RG.setText("RG:");

        LB_sexo.setText("Sexo:");

        combo_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_sexoActionPerformed(evt);
            }
        });

        LB_dtNascimento.setText("Nascimento:");

        TF_dtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_dtNascimentoActionPerformed(evt);
            }
        });

        LB_logradouro.setText("Logradouro:");

        LB_numeroEndereco.setText("Nº:");

        LB_complementoEndereco.setText("Complemento:");

        LB_bairro.setText("Bairro:");

        LB_bairro1.setText("Bairro:");

        LB_cidade.setText("Cidade:");

        combo_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cidadeActionPerformed(evt);
            }
        });

        LB_celular.setText("Celular:");

        LB_telefone.setText("Telefone:");

        LB_CEP.setText("CEP:");

        TF_CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CEPActionPerformed(evt);
            }
        });
        TF_CEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_CEPFocusLost(evt);
            }
        });

        LB_escolaridade.setText("Escolariodade:");

        combo_escolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LB_turno.setText("Turno:");

        LB_instituicao.setText("Instituição:");

        LB_curso.setText("Curso:");

        LB_situacaoCurso.setText("Situação do Curso:");

        LB_dtConclusaoCurso.setText("Data Conclusão:");

        B_limpar.setText("Limpar");
        B_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_limparActionPerformed(evt);
            }
        });

        LB_tipoLogradouro.setText("Tipo Logradouro:");

        combo_tipoLogradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " ", " " }));

        LB_UF.setText("UF:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LB_complementoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LB_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_logradouro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_logradouro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TF_complementoEndereco)
                                    .addComponent(TF_bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LB_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LB_numeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_numeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(LB_dtConclusaoCurso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_dtConclusaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(LB_situacaoCurso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combo_situacaoCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(LB_instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(combo_instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(LB_escolaridade)
                            .addGap(3, 3, 3)
                            .addComponent(combo_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(LB_turno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combo_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LB_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LB_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(combo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LB_celular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TF_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LB_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TF_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_cadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(B_limpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_nomeCandidato)
                            .addComponent(LB_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_dtNascimento))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_CPFCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_dtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo_sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_RGCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(TF_nomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_tipoLogradouro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_tipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(LB_bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(540, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_nomeCandidato)
                    .addComponent(TF_nomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_CPF)
                    .addComponent(TF_CPFCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_RG)
                    .addComponent(TF_RGCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LB_sexo)
                        .addComponent(combo_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TF_dtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LB_dtNascimento)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_tipoLogradouro)
                    .addComponent(combo_tipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_logradouro)
                    .addComponent(TF_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_complementoEndereco)
                    .addComponent(TF_complementoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_numeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_numeroEndereco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_bairro)
                    .addComponent(TF_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_CEP)
                    .addComponent(TF_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LB_UF)
                        .addComponent(TF_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LB_cidade)
                        .addComponent(combo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_telefone)
                    .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_celular)
                    .addComponent(TF_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_escolaridade)
                    .addComponent(combo_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_turno)
                    .addComponent(combo_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_instituicao)
                    .addComponent(combo_instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_curso)
                    .addComponent(combo_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_dtConclusaoCurso)
                    .addComponent(LB_situacaoCurso)
                    .addComponent(combo_situacaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_dtConclusaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_cadastrar)
                    .addComponent(B_limpar))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(249, 249, 249)
                    .addComponent(LB_bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cadastrarActionPerformed
          populaCandidato();
    }//GEN-LAST:event_B_cadastrarActionPerformed

    private void B_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_limparActionPerformed
       
    }//GEN-LAST:event_B_limparActionPerformed

    private void TF_CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CEPActionPerformed
        
    }//GEN-LAST:event_TF_CEPActionPerformed

    private void TF_CEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_CEPFocusLost
       
       logradouro = LogradouroDao.buscaPorCep(TF_CEP.getText());       
       combo_tipoLogradouro.setSelectedItem(logradouro);
       TF_logradouro.setText(logradouro.getDs_logradouro());   
       
       bairro = BairroDao.buscaBairroPorId(logradouro.getBairro().getId());
       TF_bairro.setText(bairro.getDs_bairro());
       
       cidade = CidadeDao.buscaCidadePorId(bairro.getCidade().getId());
       combo_cidade.setSelectedItem(cidade);       
       TF_UF.setText(cidade.getUf());
       
    }//GEN-LAST:event_TF_CEPFocusLost

    private void combo_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_cidadeActionPerformed

    private void TF_CPFCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CPFCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CPFCandidatoActionPerformed

    private void TF_dtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_dtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_dtNascimentoActionPerformed

    private void combo_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_sexoActionPerformed
        
    }//GEN-LAST:event_combo_sexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cadastrar;
    private javax.swing.JButton B_limpar;
    private javax.swing.JLabel LB_CEP;
    private javax.swing.JLabel LB_CPF;
    private javax.swing.JLabel LB_RG;
    private javax.swing.JLabel LB_UF;
    private javax.swing.JLabel LB_bairro;
    private javax.swing.JLabel LB_bairro1;
    private javax.swing.JLabel LB_celular;
    private javax.swing.JLabel LB_cidade;
    private javax.swing.JLabel LB_complementoEndereco;
    private javax.swing.JLabel LB_curso;
    private javax.swing.JLabel LB_dtConclusaoCurso;
    private javax.swing.JLabel LB_dtNascimento;
    private javax.swing.JLabel LB_escolaridade;
    private javax.swing.JLabel LB_instituicao;
    private javax.swing.JLabel LB_logradouro;
    private javax.swing.JLabel LB_nomeCandidato;
    private javax.swing.JLabel LB_numeroEndereco;
    private javax.swing.JLabel LB_sexo;
    private javax.swing.JLabel LB_situacaoCurso;
    private javax.swing.JLabel LB_telefone;
    private javax.swing.JLabel LB_tipoLogradouro;
    private javax.swing.JLabel LB_turno;
    private javax.swing.JTextField TF_CEP;
    private javax.swing.JTextField TF_CPFCandidato;
    private javax.swing.JTextField TF_RGCandidato;
    private javax.swing.JTextField TF_UF;
    private javax.swing.JTextField TF_bairro;
    private javax.swing.JTextField TF_celular;
    private javax.swing.JTextField TF_complementoEndereco;
    private javax.swing.JTextField TF_dtConclusaoCurso;
    private javax.swing.JTextField TF_dtNascimento;
    private javax.swing.JTextField TF_logradouro;
    private javax.swing.JTextField TF_nomeCandidato;
    private javax.swing.JTextField TF_numeroEndereco;
    private javax.swing.JTextField TF_telefone;
    private javax.swing.JComboBox combo_cidade;
    private javax.swing.JComboBox combo_curso;
    private javax.swing.JComboBox combo_escolaridade;
    private javax.swing.JComboBox combo_instituicao;
    private javax.swing.JComboBox combo_sexo;
    private javax.swing.JComboBox combo_situacaoCurso;
    private javax.swing.JComboBox combo_tipoLogradouro;
    private javax.swing.JComboBox combo_turno;
    // End of variables declaration//GEN-END:variables


    final void populaCandidato(){
       //List<Habilidade> list = new ArrayList<Habilidade>();
       
        EntityManager em = EntityManagerUtil.getEntityManager();

        GregorianCalendar data = new GregorianCalendar();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy"); 
        Date dataNas = new Date(0L);
        
        try {
            dataNas = (Date)s.parse(TF_dtNascimento.getText());            
        } catch (ParseException ex) {
            Logger.getLogger(CandidatoJF.class.getName()).log(Level.SEVERE, null, ex);
        }
        data.setTime(dataNas);
        
       candidato.setNome(TF_nomeCandidato.getText());
       candidato.setCpf(new Long(TF_CPFCandidato.getText()));
       candidato.setRg(new Long(TF_RGCandidato.getText()));
       candidato.setDt_nascimento(data);
       candidato.setSexo(combo_sexo.getSelectedItem().toString());
       logradouro = em.find(Logradouro.class, logradouro.getId());
       endereco.setLogradouro(logradouro);       
       candidato.setEndereco(endereco);
       candidato.setTelefone(TF_telefone.getText());
       candidato.setCelular(TF_celular.getText());
       candidato.setNivel_escolaridade(combo_escolaridade.getSelectedItem().toString());
       candidato.setTurno_aula(combo_turno.getSelectedItem().toString());           
       candidato.setCurso((Curso)combo_curso.getSelectedItem());
       String anoConclusao = TF_dtConclusaoCurso.getText().substring(7,10);
       candidato.setAno_conclusao(Integer.parseInt(anoConclusao));
       candidato.setStatus(combo_situacaoCurso.getSelectedItem().toString());     
       try{
         candidatoC.salvarCandidato(candidato);
       }catch(Exception e){
          e.printStackTrace();
      }
    }
       
    private void populaCurso(){
        List<Curso> c = candidatoC.popularCursos();       
       for (Curso obj : c ) { 
        combo_curso.addItem(obj);       
      }
       combo_curso.setSelectedIndex(-1);
    }     
    
    private void populaCidade(){
        List<Cidade> c = cidadeController.popularCidades();
        for(Cidade obj : c){
            combo_cidade.addItem(obj);
        }
        combo_cidade.setSelectedIndex(-1);        
    }   
     
    private void populaSexo(){
      String[] sexo = {"Masculino", "Feminino", "Transgenero"};
        for(int i=0;i<sexo.length;i++){
            combo_sexo.addItem(sexo[i]);
        }
        combo_sexo.setSelectedIndex(-1);
    }
    
    private void populaTurno(){
      String[] turno = {"Matutino", "Noturno", "Vespertino"};
        for(int i=0;i<turno.length;i++){
            combo_turno.addItem(turno[i]);
        }
        combo_turno.setSelectedIndex(-1);
    }
    
    private void populaSituacaoCurso(){
      String[] situacao = {"Aguardando Matricula", "Matriculado", "Trancado"};
        for(int i=0;i<situacao.length;i++){
            combo_situacaoCurso.addItem(situacao[i]);
        }
        combo_situacaoCurso.setSelectedIndex(-1);
    }
    
    private void populaInstituicao(){
        List<PessoaJuridica> pj = candidatoC.popularInstituicao();
        for(PessoaJuridica obj : pj){
            combo_instituicao.addItem(obj);
        }
        combo_instituicao.setSelectedIndex(-1);
    }
}
