/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estagio.view;

import br.com.estagio.model.Candidato;
import br.com.estagio.model.CandidatoVaga;
import br.com.estagio.model.Curso;
import br.com.estagio.model.Habilidade;
import br.com.estagio.model.PessoaJuridica;
import br.com.estagio.model.Vaga;
import controller.CandidatoVagaController;
import controller.VagaCandidatoController;
import controller.VagaController;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victor
 */
public class CandidatoVagaJF extends javax.swing.JInternalFrame {

    Date dataAtual; 
    Vaga vaga;
    List<Curso> listCurso;
    List<PessoaJuridica> listPJ;
    VagaController vagaC;
    DefaultListModel lm;
    List<Habilidade> listH;
    List<Habilidade> h;
    DefaultTableModel mTable;
    Candidato cand;
    CandidatoVagaController VagaCandC;
    CandidatoVaga candV;
    
    public CandidatoVagaJF() {
        initComponents();
        
        h = null;
        vaga = new Vaga();
        listCurso = new ArrayList<Curso>();
        listPJ = new ArrayList<PessoaJuridica>();
        vagaC = new VagaController();
        listH = new ArrayList<Habilidade>();
        h = new ArrayList<Habilidade>();
        mTable = (DefaultTableModel)jTable.getModel();
        habilitaCamposIni(true);
        populaEmpresa();
        cand = new Candidato();
        VagaCandC = new CandidatoVagaController();
        candV = new CandidatoVaga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Combo_Empresa = new javax.swing.JComboBox();
        LB_empresa = new javax.swing.JLabel();
        Sep_formulario = new javax.swing.JSeparator();
        LB_pesquisar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        LB_codigo = new javax.swing.JLabel();
        TF_codigo = new javax.swing.JTextField();
        B_gravar = new javax.swing.JButton();
        B_buscar = new javax.swing.JButton();
        Sep_formulario1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Vagas");
        setAutoscrolls(true);

        Combo_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_EmpresaActionPerformed(evt);
            }
        });

        LB_empresa.setText("Empresa:");

        LB_pesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_pesquisar.setText("Pesquisar:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Empresa", "Curso", "Turno", "Data Cadastro", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable);

        LB_codigo.setText("Código:");

        TF_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_codigoActionPerformed(evt);
            }
        });

        B_gravar.setText("Cancelar Candidatura");
        B_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_gravarActionPerformed(evt);
            }
        });

        B_buscar.setText("Buscar");
        B_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep_formulario1)
            .addComponent(Sep_formulario)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(LB_pesquisar)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LB_empresa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Combo_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_codigo)
                                        .addGap(122, 122, 122)
                                        .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(167, 167, 167)
                                .addComponent(B_buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(B_gravar)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sep_formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_pesquisar)
                    .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_codigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_empresa))
                .addGap(18, 18, 18)
                .addComponent(B_buscar)
                .addGap(41, 41, 41)
                .addComponent(Sep_formulario1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(B_gravar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_gravarActionPerformed
         Long vagaId; 
         CandidatoVaga vagaSelec = new CandidatoVaga();
         
        try{ 
         vagaId = (Long)mTable.getValueAt(jTable.getSelectedRow(),0);
       // vagaSelec = vagaC.preencherCampos((Long)mTable.getValueAt(jTable.getSelectedRow(),0));  
        
        VagaCandC.excluirVagaCandidato(vagaId, cand);
         JOptionPane.showMessageDialog(rootPane, "Voce se candidatou à vaga com sucesso!");
        }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane, "Não foi possível se candidatar à vaga!");  
        }
    }//GEN-LAST:event_B_gravarActionPerformed

    private void B_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarActionPerformed
         Long cod = null;
         Curso c = null;
         PessoaJuridica p = null;
         Long candId = null;
         
          try { 
        
          p = (PessoaJuridica)Combo_Empresa.getSelectedItem();
          cod = Long.valueOf(TF_codigo.getText());
          
          }catch(NumberFormatException e){
             
               }catch(ClassCastException cl){
           
          }
         mTable.setNumRows(0);
        
         if(!VagaCandC.pupularTabela(mTable,cod,c,p, candId)){
           
             JOptionPane.showMessageDialog(rootPane, "Um ou mais campos não foram preenchidos!");
          }
        
         
    }//GEN-LAST:event_B_buscarActionPerformed

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
       
    }//GEN-LAST:event_jTableMousePressed

    private void TF_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_codigoActionPerformed

    private void Combo_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_EmpresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_buscar;
    private javax.swing.JButton B_gravar;
    private javax.swing.JComboBox Combo_Empresa;
    private javax.swing.JLabel LB_codigo;
    private javax.swing.JLabel LB_empresa;
    private javax.swing.JLabel LB_pesquisar;
    private javax.swing.JSeparator Sep_formulario;
    private javax.swing.JSeparator Sep_formulario1;
    private javax.swing.JTextField TF_codigo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables


    final void populaVaga(){
       //List<Habilidade> list = new ArrayList<Habilidade>();
    
    }
       
     private void populaEmpresa(){
        //DefaultComboBoxModel model = new DefaultComboBoxModel(); 
        List<PessoaJuridica> p = vagaC.popularEmpresas();
        
        Combo_Empresa.addItem(null);
         for (PessoaJuridica obj : p ) { 
          
             Combo_Empresa.addItem(obj);
         }
       Combo_Empresa.setSelectedIndex(-1);
    }

    private void habilitaCampos(boolean valor){
       
        Combo_Empresa.setEnabled(valor);
         B_gravar.setEnabled(!valor);
      
                
    }  
    
     private void habilitaCamposIni(boolean valor){
     
        Combo_Empresa.setEnabled(valor);
        B_gravar.setEnabled(valor);
        
    }   

     
}
