/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estagio.view;

import br.com.estagio.model.Curso;
import br.com.estagio.model.Habilidade;
import br.com.estagio.model.PessoaJuridica;
import br.com.estagio.model.Vaga;
import controller.VagaController;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;

/**
 *
 * @author victor
 */
public class VagaJF extends javax.swing.JInternalFrame {

    Calendar dataAtual; 
    Vaga vaga;
    List<Curso> listCurso;
    List<PessoaJuridica> listPJ;
    VagaController vagaC;
    DefaultListModel lm;
    List<Habilidade> listH;
    List<Habilidade> h;
    
    public VagaJF() {
        initComponents();
        
        h = null;
        vaga = new Vaga();
        listCurso = new ArrayList<Curso>();
        listPJ = new ArrayList<PessoaJuridica>();
        vagaC = new VagaController();
        listH = new ArrayList<Habilidade>();
        h = new ArrayList<Habilidade>();
    
       populaCurso();
       populaEmpresa();
       popularJList1();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbEstagioPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("dbEstagioPU").createEntityManager();
        habilidadeQuery = java.beans.Beans.isDesignTime() ? null : dbEstagioPUEntityManager.createQuery("SELECT h FROM Habilidade h");
        habilidadeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : habilidadeQuery.getResultList();
        Combo_Empresa = new javax.swing.JComboBox();
        LB_empresa = new javax.swing.JLabel();
        Combo_turno = new javax.swing.JComboBox();
        LB_turno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_descricao = new javax.swing.JTextArea();
        LB_descricao = new javax.swing.JLabel();
        LB_beneficios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA_beneficios = new javax.swing.JTextArea();
        LB_bolsa = new javax.swing.JLabel();
        TF_bolsa = new javax.swing.JTextField();
        Sep_formulario = new javax.swing.JSeparator();
        LB_pesquisar = new javax.swing.JLabel();
        LB_curso = new javax.swing.JLabel();
        Combo_curso = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LB_codigo = new javax.swing.JLabel();
        TF_codigo = new javax.swing.JTextField();
        B_novo = new javax.swing.JButton();
        B_cadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        m1 = new DefaultListModel();
        jList1 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        m2 = new DefaultListModel();
        jList2 = new javax.swing.JList();
        B_add = new javax.swing.JButton();
        B_rmv = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Vagas");
        setAutoscrolls(true);

        LB_empresa.setText("Empresa:");

        Combo_turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino", "Noturno", "Diurno" }));
        Combo_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_turnoActionPerformed(evt);
            }
        });

        LB_turno.setText("Turno:");

        TA_descricao.setColumns(20);
        TA_descricao.setRows(5);
        jScrollPane1.setViewportView(TA_descricao);

        LB_descricao.setText("Descrição:");

        LB_beneficios.setText("Benefícios:");

        TA_beneficios.setColumns(20);
        TA_beneficios.setRows(5);
        jScrollPane2.setViewportView(TA_beneficios);

        LB_bolsa.setText("Valor Bolsa:");

        LB_pesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_pesquisar.setText("Pesquisar:");

        LB_curso.setText("Curso:");

        Combo_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_cursoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Empresa", "Curso", "Turno", "Data Cadastro", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        LB_codigo.setText("Código:");

        B_novo.setText("Novo");
        B_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novoActionPerformed(evt);
            }
        });

        B_cadastrar.setText("Cadastrar");
        B_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cadastrarActionPerformed(evt);
            }
        });

        jList1.setModel(m1);
        jList1.setToolTipText("õnon");
        jScrollPane4.setViewportView(jList1);

        jList2.setModel(m2);
        jList2.setToolTipText("");
        jScrollPane5.setViewportView(jList2);

        B_add.setText(">>");
        B_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_addActionPerformed(evt);
            }
        });

        B_rmv.setText("<<");
        B_rmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_rmvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_rmv, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(B_add)
                            .addGap(18, 18, 18)
                            .addComponent(B_rmv))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LB_curso)
                                    .addComponent(LB_turno)
                                    .addComponent(LB_empresa)
                                    .addComponent(LB_descricao))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_bolsa)
                                    .addComponent(LB_beneficios))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combo_Empresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_turno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_curso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TF_bolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LB_pesquisar)
                        .addGap(42, 42, 42)
                        .addComponent(LB_codigo)
                        .addGap(18, 18, 18)
                        .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(B_novo)
                        .addGap(69, 69, 69)
                        .addComponent(B_cadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(Sep_formulario, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_empresa)
                            .addComponent(Combo_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_curso)
                            .addComponent(Combo_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_turno)
                            .addComponent(Combo_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LB_descricao)
                                .addGap(60, 60, 60)
                                .addComponent(LB_beneficios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_bolsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_bolsa)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Sep_formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_pesquisar)
                    .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_codigo))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_novo)
                    .addComponent(B_cadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_novoActionPerformed

    private void B_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cadastrarActionPerformed
        // TODO add your handling code here:
        populaVaga();
    }//GEN-LAST:event_B_cadastrarActionPerformed

    private void Combo_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_cursoActionPerformed

    private void Combo_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_turnoActionPerformed

    private void B_rmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_rmvActionPerformed
       Habilidade h2 = new Habilidade();
       
        h2 = (Habilidade)jList2.getSelectedValue();
        h.remove(h2);
        m1.addElement(jList2.getSelectedValue());
        m2.removeElement(jList2.getSelectedValue());
       
        jList1.setSelectedIndex(0);
        jList2.setSelectedIndex(0);
    }//GEN-LAST:event_B_rmvActionPerformed

    private void B_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_addActionPerformed
       Habilidade h1 = new Habilidade();
    
       h1 = (Habilidade)jList1.getSelectedValue();
       h.add(h1);
       m2.addElement(jList1.getSelectedValue());
       m1.removeElement(jList1.getSelectedValue());
     
       jList2.setSelectedIndex(0);
       jList1.setSelectedIndex(0);
    }//GEN-LAST:event_B_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_add;
    private javax.swing.JButton B_cadastrar;
    private javax.swing.JButton B_novo;
    private javax.swing.JButton B_rmv;
    private javax.swing.JComboBox Combo_Empresa;
    private javax.swing.JComboBox Combo_curso;
    private javax.swing.JComboBox Combo_turno;
    private javax.swing.JLabel LB_beneficios;
    private javax.swing.JLabel LB_bolsa;
    private javax.swing.JLabel LB_codigo;
    private javax.swing.JLabel LB_curso;
    private javax.swing.JLabel LB_descricao;
    private javax.swing.JLabel LB_empresa;
    private javax.swing.JLabel LB_pesquisar;
    private javax.swing.JLabel LB_turno;
    private javax.swing.JSeparator Sep_formulario;
    private javax.swing.JTextArea TA_beneficios;
    private javax.swing.JTextArea TA_descricao;
    private javax.swing.JTextField TF_bolsa;
    private javax.swing.JTextField TF_codigo;
    private javax.persistence.EntityManager dbEstagioPUEntityManager;
    private java.util.List<br.com.estagio.model.Habilidade> habilidadeList;
    private javax.persistence.Query habilidadeQuery;
    private javax.swing.JList jList1;
    private DefaultListModel m1;
    private javax.swing.JList jList2;
    private DefaultListModel m2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


    final void populaVaga(){
       //List<Habilidade> list = new ArrayList<Habilidade>();
       vaga.setCurso((Curso)Combo_curso.getSelectedItem());
       vaga.setDescricao(TA_descricao.getText());
       vaga.setDs_beneficio(TA_beneficios.getText());
       vaga.setEmpresa((PessoaJuridica) Combo_Empresa.getSelectedItem());
       vaga.setStatus("D");
       vaga.setTurno(Combo_turno.getSelectedItem().toString());
       vaga.setValor_bolsa(Integer.parseInt(TF_bolsa.getText()));
       vaga.setHabilidades(h);
       
       System.out.println("chegou aqui");
       System.out.println(h.size());
       for(Habilidade lista:h){
     
       System.out.println(lista.getDescricao());
      
       }
    }
    
    private void populaCurso(){
        List<Curso> c = vagaC.popularCursos();
       
         for (Curso obj : c ) { 
        Combo_curso.addItem(obj);
       
      }
    }     
   
     private void populaEmpresa(){
        //DefaultComboBoxModel model = new DefaultComboBoxModel(); 
        List<PessoaJuridica> p = vagaC.popularEmpresas();
         for (PessoaJuridica obj : p ) { 
          
             Combo_Empresa.addItem(obj);
         }
       
    }

    private void popularJList1() {
        listH = vagaC.pupulaHabilidades();
        for(Habilidade obj:listH){
        
        m1.addElement(obj);
        }
        
    }

     
    
}
