/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estagio.view;

import br.com.estagio.model.Curso;
import br.com.estagio.model.Habilidade;
import br.com.estagio.model.PessoaJuridica;
import br.com.estagio.model.Vaga;
import controller.VagaController;
import java.awt.event.ItemListener;
import java.text.ParseException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victor
 */
public class VagaJF extends javax.swing.JInternalFrame {

    Date dataAtual; 
    Vaga vaga;
    List<Curso> listCurso;
    List<PessoaJuridica> listPJ;
    VagaController vagaC;
    DefaultListModel lm;
    List<Habilidade> listH;
    List<Habilidade> h;
    DefaultTableModel mTable;
    
    public VagaJF() {
        initComponents();
        
        h = null;
        vaga = new Vaga();
        listCurso = new ArrayList<Curso>();
        listPJ = new ArrayList<PessoaJuridica>();
        vagaC = new VagaController();
        listH = new ArrayList<Habilidade>();
        h = new ArrayList<Habilidade>();
        mTable = (DefaultTableModel)jTable.getModel();
        habilitaCamposIni(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Combo_Empresa = new javax.swing.JComboBox();
        LB_empresa = new javax.swing.JLabel();
        Combo_turno = new javax.swing.JComboBox();
        LB_turno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_descricao = new javax.swing.JTextArea();
        LB_descricao = new javax.swing.JLabel();
        LB_beneficios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA_beneficios = new javax.swing.JTextArea();
        LB_bolsa = new javax.swing.JLabel();
        /*MaskFormatter mascaraCampo = null;
        try {
            mascaraCampo= new MaskFormatter("#.###,##");
        }catch (ParseException e) {
        }*/
        TF_bolsa = new javax.swing.JTextField();
        Sep_formulario = new javax.swing.JSeparator();
        LB_pesquisar = new javax.swing.JLabel();
        LB_curso = new javax.swing.JLabel();
        Combo_curso = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        LB_codigo = new javax.swing.JLabel();
        TF_codigo = new javax.swing.JTextField();
        B_novo = new javax.swing.JButton();
        B_gravar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        m1 = new DefaultListModel();
        jList1 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        m2 = new DefaultListModel();
        jList2 = new javax.swing.JList();
        B_add = new javax.swing.JButton();
        B_rmv = new javax.swing.JButton();
        B_buscar = new javax.swing.JButton();
        B_alterar = new javax.swing.JButton();
        B_excluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Vagas");
        setAutoscrolls(true);

        Combo_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_EmpresaActionPerformed(evt);
            }
        });

        LB_empresa.setText("Empresa:");

        Combo_turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino", "Noturno", "Diurno" }));
        Combo_turno.setSelectedIndex(-1);
        Combo_turno.setToolTipText("");
        Combo_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_turnoActionPerformed(evt);
            }
        });

        LB_turno.setText("Turno:");

        TA_descricao.setColumns(20);
        TA_descricao.setRows(5);
        jScrollPane1.setViewportView(TA_descricao);

        LB_descricao.setText("Descrição:");

        LB_beneficios.setText("Benefícios:");

        TA_beneficios.setColumns(20);
        TA_beneficios.setRows(5);
        jScrollPane2.setViewportView(TA_beneficios);

        LB_bolsa.setText("Valor Bolsa:");

        //JFormattedTextField TF_bolsa = new JFormattedTextField(mascaraCampo);

        LB_pesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_pesquisar.setText("Pesquisar:");

        LB_curso.setText("Curso:");

        Combo_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_cursoActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Empresa", "Curso", "Turno", "Data Cadastro", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable);

        LB_codigo.setText("Código:");

        TF_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_codigoActionPerformed(evt);
            }
        });

        B_novo.setText("Novo");
        B_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novoActionPerformed(evt);
            }
        });

        B_gravar.setText("Gravar");
        B_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_gravarActionPerformed(evt);
            }
        });

        jList1.setModel(m1);
        jList1.setToolTipText("õnon");
        jScrollPane4.setViewportView(jList1);

        jList2.setModel(m2);
        jList2.setToolTipText("");
        jScrollPane5.setViewportView(jList2);

        B_add.setText(">>");
        B_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_addActionPerformed(evt);
            }
        });

        B_rmv.setText("<<");
        B_rmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_rmvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_rmv, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(B_add)
                            .addGap(18, 18, 18)
                            .addComponent(B_rmv))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        B_buscar.setText("Buscar");
        B_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarActionPerformed(evt);
            }
        });

        B_alterar.setText("Alterar");
        B_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_alterarActionPerformed(evt);
            }
        });

        B_excluir.setText("Excluir");
        B_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LB_curso)
                                    .addComponent(LB_turno)
                                    .addComponent(LB_empresa)
                                    .addComponent(LB_descricao))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_bolsa)
                                    .addComponent(LB_beneficios))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combo_Empresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_turno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_curso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TF_bolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LB_pesquisar)
                        .addGap(42, 42, 42)
                        .addComponent(LB_codigo)
                        .addGap(18, 18, 18)
                        .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(B_buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(B_novo)
                        .addGap(97, 97, 97)
                        .addComponent(B_alterar)
                        .addGap(99, 99, 99)
                        .addComponent(B_excluir)
                        .addGap(119, 119, 119)
                        .addComponent(B_gravar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(Sep_formulario, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_empresa)
                            .addComponent(Combo_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_curso)
                            .addComponent(Combo_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_turno)
                            .addComponent(Combo_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LB_descricao)
                                .addGap(60, 60, 60)
                                .addComponent(LB_beneficios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_bolsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_bolsa)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Sep_formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_pesquisar)
                    .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_codigo)
                    .addComponent(B_buscar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_novo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_alterar)
                        .addComponent(B_gravar)
                        .addComponent(B_excluir)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novoActionPerformed
       limpaFormaulario();
       populaCurso();
       populaEmpresa();
       popularJList1();
       habilitaCampos(true);
    }//GEN-LAST:event_B_novoActionPerformed

    private void B_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_gravarActionPerformed
        // TODO add your handling code here:
        if (TA_beneficios.getText().isEmpty() || TA_descricao.getText().isEmpty() || Combo_curso.getSelectedItem() == null || 
            Combo_Empresa.getSelectedItem() == null || Combo_turno.getSelectedItem() == null || TF_bolsa.getText().isEmpty() ||  h.size() == 0) {  // ou texto.trim().isEmpty()  
               
        // campo vazio = mensagem de erro?  
         JOptionPane.showMessageDialog(rootPane, "Um ou mais campos não foram preenchidos!");
         
        }else {       
        populaVaga();
        
        }
    }//GEN-LAST:event_B_gravarActionPerformed

    private void Combo_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_cursoActionPerformed

    private void Combo_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_turnoActionPerformed

    private void B_rmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_rmvActionPerformed
       Habilidade h2 = new Habilidade();
       
        h2 = (Habilidade)jList2.getSelectedValue();
        h.remove(h2);
        m1.addElement(h2);
        m2.removeElementAt(jList2.getSelectedIndex());
        
        jList1.setSelectedIndex(0);
        jList2.setSelectedIndex(0);
    }//GEN-LAST:event_B_rmvActionPerformed

    private void B_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_addActionPerformed
       Habilidade h1 = new Habilidade();
    
       h1 = (Habilidade)jList1.getSelectedValue();
       h.add(h1);
       m2.addElement(h1);
       m1.remove(jList1.getSelectedIndex());
      
       
       
       jList2.setSelectedIndex(0);
       jList1.setSelectedIndex(0);
    }//GEN-LAST:event_B_addActionPerformed

    private void B_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarActionPerformed
         B_alterar.setEnabled(true);
          B_excluir.setEnabled(true);
         
         mTable.setNumRows(0);
      if(TF_codigo.getText().isEmpty()){   
        vagaC.pupularTabela(mTable, null);
      }else{ 
      vagaC.pupularTabela(mTable,Integer.valueOf(TF_codigo.getText())); 
      }
    }//GEN-LAST:event_B_buscarActionPerformed

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
        B_alterar.setEnabled(true);
         B_excluir.setEnabled(true);
    }//GEN-LAST:event_jTableMousePressed

    private void B_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_alterarActionPerformed
        limpaFormaulario();
        habilitaCampos(true);
         populaEmpresa();
         populaCurso();
         popularJList1();
       
       // System.out.println(mTable.getValueAt(jTable.getSelectedRow(),0));
       vaga = vagaC.preencherCampos((Long)mTable.getValueAt(jTable.getSelectedRow(),0));
       
       TF_bolsa.setText(vaga.getValor_bolsa().toString());
       Combo_Empresa.setSelectedItem(vaga.getEmpresa());
       Combo_curso.setSelectedItem(vaga.getCurso());
       Combo_turno.setSelectedItem(vaga.getTurno());
       TA_beneficios.setText(vaga.getDs_beneficio());
       TA_descricao.setText(vaga.getDescricao());
       popularJList2(vaga);
       
       
    }//GEN-LAST:event_B_alterarActionPerformed

    private void Combo_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_EmpresaActionPerformed

    private void B_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_excluirActionPerformed
       
        vagaC.exluirVaga((Long)mTable.getValueAt(jTable.getSelectedRow(),0));
        JOptionPane.showMessageDialog(rootPane, "Vaga excluida com sucesso!");
        B_buscarActionPerformed(evt);
      
    }//GEN-LAST:event_B_excluirActionPerformed

    private void TF_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_codigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_add;
    private javax.swing.JButton B_alterar;
    private javax.swing.JButton B_buscar;
    private javax.swing.JButton B_excluir;
    private javax.swing.JButton B_gravar;
    private javax.swing.JButton B_novo;
    private javax.swing.JButton B_rmv;
    private javax.swing.JComboBox Combo_Empresa;
    private javax.swing.JComboBox Combo_curso;
    private javax.swing.JComboBox Combo_turno;
    private javax.swing.JLabel LB_beneficios;
    private javax.swing.JLabel LB_bolsa;
    private javax.swing.JLabel LB_codigo;
    private javax.swing.JLabel LB_curso;
    private javax.swing.JLabel LB_descricao;
    private javax.swing.JLabel LB_empresa;
    private javax.swing.JLabel LB_pesquisar;
    private javax.swing.JLabel LB_turno;
    private javax.swing.JSeparator Sep_formulario;
    private javax.swing.JTextArea TA_beneficios;
    private javax.swing.JTextArea TA_descricao;
    private javax.swing.JTextField TF_bolsa;
    private javax.swing.JTextField TF_codigo;
    private javax.swing.JList jList1;
    private DefaultListModel m1;
    private javax.swing.JList jList2;
    private DefaultListModel m2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables


    final void populaVaga(){
       //List<Habilidade> list = new ArrayList<Habilidade>();
        dataAtual = new Date();
       vaga.setCurso((Curso)Combo_curso.getSelectedItem());
       vaga.setDescricao(TA_descricao.getText());
       vaga.setDs_beneficio(TA_beneficios.getText());
       vaga.setEmpresa((PessoaJuridica) Combo_Empresa.getSelectedItem());
       vaga.setStatus("D");
       vaga.setTurno(Combo_turno.getSelectedItem().toString());
       vaga.setValor_bolsa(Integer.parseInt(TF_bolsa.getText()));
       vaga.setHabilidades(h);
       vaga.setDt_cadastro(dataAtual);
       System.out.println(h.size());
       
       try{
       
       vagaC.salvarVaga(vaga);
       JOptionPane.showMessageDialog(rootPane, "Vaga gravada com sucesso!");
       limpaFormaulario();
       B_buscarActionPerformed(null);
       }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "Houve um problema ao gravar a vaga!");    
       e.printStackTrace();
       }
     
    }
       
    private void populaCurso(){
        List<Curso> c = vagaC.popularCursos();
       
       for (Curso obj : c ) { 
        Combo_curso.addItem(obj);
       
      }
       Combo_curso.setSelectedIndex(-1);
    }     
   
     private void populaEmpresa(){
        //DefaultComboBoxModel model = new DefaultComboBoxModel(); 
        List<PessoaJuridica> p = vagaC.popularEmpresas();
        
         for (PessoaJuridica obj : p ) { 
          
             Combo_Empresa.addItem(obj);
         }
       Combo_Empresa.setSelectedIndex(-1);
    }

    private void popularJList1() {
        listH = vagaC.pupulaHabilidades();
        for(Habilidade obj:listH){
        
        m1.addElement(obj);
        }
        
    }

    private void habilitaCampos(boolean valor){
        TF_bolsa.setEditable(valor);
        Combo_Empresa.setEnabled(valor);
        Combo_curso.setEnabled(valor);
        Combo_turno.setEnabled(valor);
        TA_beneficios.setEditable(valor);
        TA_descricao.setEditable(valor);
        jList1.setEnabled(valor);
        jList2.setEnabled(valor);
        B_gravar.setEnabled(true);
        B_alterar.setEnabled(!valor);
        B_excluir.setEnabled(!valor);
                
    }  
    
     private void habilitaCamposIni(boolean valor){
        TF_bolsa.setEditable(valor);
        Combo_Empresa.setEnabled(valor);
        Combo_curso.setEnabled(valor);
        Combo_turno.setEnabled(valor);
        TA_beneficios.setEditable(valor);
        TA_descricao.setEditable(valor);
        jList1.setEnabled(valor);
        jList2.setEnabled(valor);
        B_alterar.setEnabled(valor);
        B_excluir.setEnabled(valor);
        B_gravar.setEnabled(valor);
        
    }   

    private void popularJList2(Vaga vaga) {
           h = (List<Habilidade>) vaga.getHabilidades();
            for(Habilidade obj:vaga.getHabilidades()){
                m2.addElement(obj);
        }
    }

    private void limpaFormaulario() {
        
       TF_bolsa.setText("");
       Combo_Empresa.removeAllItems();
       Combo_Empresa.setSelectedIndex(-1);
       Combo_curso.removeAllItems();
       Combo_curso.setSelectedIndex(-1);
       Combo_turno.setSelectedIndex(-1);
       TA_beneficios.setText("");
       TA_descricao.setText("");
       m1.clear();
       m2.clear();
       h.clear();
       habilitaCampos(false);
       
    }
    
}
